twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%env(APP_NAME)%'
        app_title: '%env(APP_TITLE)%'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        strict_variables: true
